### PR TITLE
GraphQL/FieldUniqueness: Consider camelized and non-camelized versions of a field as distinct

### PR DESCRIPTION
**Pull request by severin**
Addresses https://github.com/DmitryTsepelev/rubocop-graphql/issues/147

### CODE REVIEW

**Comment by DmitryTsepelev** [comment]
Hey @severin is it ready? 🙂

**Comment by severin** [comment]
@DmitryTsepelev I did not work further on it yet, I first wanted to know whether you consider it an issue worth fixing or not. I take your comment as an affirmation and will work on it to polish it 🙂

**Comment by DmitryTsepelev** [comment]
oh shoot I missed that you're missing my input 🤦‍♂️yes yes, your proposal makes a lot of sense!

**Comment by severin** [comment]
@DmitryTsepelev I finally found some time to tidy up the code and I opened a PR against your repo: https://github.com/DmitryTsepelev/rubocop-graphql/pull/152

**Pull request closed without merging**
